### ISSUE TITLE
Esys called in bad sequence.

### ISSUE THREAD

**Issue by warusadura** [dnuka/tpmsecret#1]
I'm trying to create a primary key (RSA) first and then a second key (AES). And I'm not sure why I'm getting the following error,

```
ERROR:esys:src/tss2-esys/esys_iutil.c:1144:iesys_check_sequence_async() Esys called in bad sequence. 
ERROR:esys:src/tss2-esys/api/Esys_Create.c:96:Esys_Create() Error in async function ErrorCode (0x00070007)
```

Reference: [esys-unseal-password-auth.int.c](https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-unseal-password-auth.int.c)

**Comment by warusadura** [comment]
cc @ueno @ansasaki @PeterHuewe @AndreasFuchsSIT

**Comment by AndreasFuchsTPM** [comment]
You finalize the context here:
https://github.com/dnuka/tpmsecret/blob/d6948cce8386e74ee8b852ba8d7314dc1cd25627/src/primarykey.c#L107

So later use is not possible...

**Comment by warusadura** [comment]
Oh! I see. Thanks @AndreasFuchsSIT
